/*The sequence of triangle numbers is generated by adding the
 * natural numbers. So the 7th triangle number would be
 * 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 *
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * 
 * Let us list the factors of the first seven triangle numbers:
 *
 * 1: 1
 * 3: 1,3
 * 6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * 
 * We can see that 28 is the first triangle number to have over five divisors.
 * What is the value of the first triangle number to have
 * over five hundred divisors?
 */



function numDivisors(num) {
	var index, counter;
	
	counter = 1;

	for (index = 1; index <= num/2; index++){
		if (!(num % index)) {
			counter++;
		}
	}
	
	return counter;
}

function triangleNumbers(maxDivisors) {
	var index, number, divisors;
	
	index = 2;
	number = 1;
	divisors  = 0;
	
	while (divisors <= maxDivisors) {
		number += index;
		index++;
		divisors =  numDivisors(number);
	}

	console.log(number);
	
	return number;
}

triangleNumbers(300);
//triangleNumbers(350) = 17907120


















